class SettingsManager:
    def __init__(self, name, settings_directory = None) -> None: ...
    """Initializes the settings manager."""
    def read(self): ...
    """Reads the settings file."""
    def commit(self): ...
    """Writes to the settings file."""
    def getSetting(self, key, default): ...
    """Gets the value for a setting from the settings file."""
    def setSetting(self, key, value): ...
    """Sets the value for a setting in the settings file and commits it."""